import esbuild from "esbuild";
import postcss from "postcss";
import postcssNesting from "postcss-nesting";
import { builtinModules } from "node:module";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const distDir = path.join(projectRoot, "dist");
const localSyncScript = path.join(projectRoot, "scripts", "copy-to-vault.mjs");
const deployFiles = ["main.js", "manifest.json", "styles.css"];
const prod = process.argv[2] === "production";
const keepConsole = process.argv[3] === "keep-console";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

async function assertSafeDistTree(directory) {
	for (const entry of await fs.readdir(directory)) {
		const item = path.join(directory, entry);
		const info = await fs.lstat(item);
		if (info.isSymbolicLink()) throw new Error(`dist 含有目录联接或符号链接: ${item}`);
		if (!info.isDirectory()) continue;
		const relative = path.relative(distDir, await fs.realpath(item));
		if (relative.startsWith("..") || path.isAbsolute(relative)) {
			throw new Error(`dist 子目录越界: ${item}`);
		}
		await assertSafeDistTree(item);
	}
}

async function prepareDist() {
	if (path.relative(projectRoot, distDir) !== "dist") {
		throw new Error(`构建目录不在项目根目录下: ${distDir}`);
	}
	try {
		const info = await fs.lstat(distDir);
		if (!info.isDirectory() || info.isSymbolicLink() ||
			path.normalize(await fs.realpath(distDir)).toLowerCase() !== path.normalize(distDir).toLowerCase()) {
			throw new Error(`构建目录不是项目内的普通目录: ${distDir}`);
		}
		await assertSafeDistTree(distDir);
		await fs.rm(distDir, { recursive: true });
	} catch (error) {
		if (error?.code !== "ENOENT") throw error;
	}
	await fs.mkdir(distDir);
}

async function validateDist() {
	const entries = (await fs.readdir(distDir)).sort();
	if (JSON.stringify(entries) !== JSON.stringify([...deployFiles].sort())) {
		throw new Error(`dist 内容不符合部署范围: ${entries.join(", ")}`);
	}
	for (const name of deployFiles) {
		const info = await fs.lstat(path.join(distDir, name));
		if (!info.isFile() || info.isSymbolicLink() || info.size === 0) {
			throw new Error(`构建产物无效: ${name}`);
		}
	}
}

async function syncWithLocalScript() {
	let info;
	try {
		info = await fs.lstat(localSyncScript);
	} catch (error) {
		if (error?.code !== "ENOENT") throw error;
		console.warn("未找到本地同步脚本: dist 已生成, 插件同步未完成");
		return;
	}
	if (!info.isFile() || info.isSymbolicLink()) throw new Error("本地同步脚本不是普通文件");
	const { syncToVault } = await import(pathToFileURL(localSyncScript).href);
	if (typeof syncToVault !== "function") throw new Error("本地同步脚本缺少 syncToVault 函数");
	await syncToVault();
}

const deploymentArtifacts = {
	name: "deployment-artifacts",
	setup(build) {
		build.onStart(prepareDist);
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;
			try {
				await fs.rename(path.join(distDir, "main.css"), path.join(distDir, "styles.css"));
				await fs.copyFile(path.join(projectRoot, "manifest.json"), path.join(distDir, "manifest.json"));
				await validateDist();
				await syncWithLocalScript();
			} catch (error) {
				return { errors: [{ text: error instanceof Error ? error.message : String(error) }] };
			}
		});
	},
};

const cssRebuild = {
	name: "css-rebuild",
	setup(build) {
		build.onLoad({ filter: /\.css$/ }, async (args) => {
			try {
				const css = await fs.readFile(args.path, "utf8");
				const result = await postcss([postcssNesting]).process(css, { from: args.path });
				return { contents: result.css, loader: "css" };
			} catch (error) {
				return { errors: [{ text: error instanceof Error ? error.message : String(error) }] };
			}
		});
	},
};

const context = await esbuild.context({
	absWorkingDir: projectRoot,
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [deploymentArtifacts, cssRebuild],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((moduleName) => `node:${moduleName}`),
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(distDir, "main.js"),
	minify: prod,
	drop: prod && !keepConsole ? ["console"] : [],
	loader: { ".ttf": "base64" },
});

if (prod) {
	try {
		await context.rebuild();
	} finally {
		await context.dispose();
	}
} else {
	await context.watch();
}
